### ISSUE TITLE
Descrizione del problema

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/simpletron#1]
![schermata da 2015-12-17 21-50-12](https://cloud.githubusercontent.com/assets/3002194/11902217/73c4c538-a5b0-11e5-8587-0cff597bf990.png)
![schermata da 2015-12-17 21-50-25](https://cloud.githubusercontent.com/assets/3002194/11902219/73ca48c8-a5b0-11e5-81cf-2c35dbc28e27.png)
![schermata da 2015-12-17 21-50-35](https://cloud.githubusercontent.com/assets/3002194/11902218/73ca296a-a5b0-11e5-85b6-9c17148ed049.png)
![schermata da 2015-12-17 21-50-46](https://cloud.githubusercontent.com/assets/3002194/11902220/73d03ab2-a5b0-11e5-9b47-3c75192029ce.png)
![schermata da 2015-12-17 21-51-00](https://cloud.githubusercontent.com/assets/3002194/11902221/73e1be90-a5b0-11e5-94d9-b6344a97aae3.png)

Non scrivere codice per il momento

**Comment by luca998** [comment]
Va bene

**Comment by FabioZTessitore** [comment]
Studiati bene il problema e cerca di scrivere (a mano) un programma che fa la media di due numeri interi dati in input

**Comment by luca998** [comment]
| Locazione | Numero | Istruzione |
| --- | --- | --- |
| 00 | +1009 | Leggi A |
| 01 | +1010 | Leggi B |
| 02 | +1011 | Leggi 2 |
| 03 | +2009 | Carica A nell'accumulatore |
| 04 | +3010 | Somma B all'accumulatore |
| 05 | +3211 | Dividi 2 all'accumulatore |
| 06 | +2112 | Memorizza il valore dell'accumulatore in C |
| 07 | +1112 | Stampa C |
| 08 | +4300 | Halt |
| 09 | +0000 | Variabile A |
| 10 | +0000 | Variabile B |
| 11 | +0000 | 2 |
| 12 | +0000 | Risultato C |

**Comment by FabioZTessitore** [comment]
sei sicuro di sapere come si fa la media tra due numeri?

Il giorno 30 gennaio 2016 16:34, luca998 notifications@github.com ha
scritto:

**Comment by luca998** [comment]
ah la media hahah

**Comment by luca998** [comment]
ho modificato il commento

**Comment by FabioZTessitore** [comment]
quasi bene, non credo abbia molto senso fargli leggere il due. Potresti metterlo direttamente nella cella di memoria

**Comment by FabioZTessitore** [comment]
Locazione │ Numero │ Istruzione
------------ | ------ | --------

00                     │   +1009                  │            Leggi A
01                     │   +1010                  │            Leggi B
02                     │   +1011                  │            Leggi 2
03                     │   +2009                  │            Carica A nell'accumulatore
04                     │   +3010                  │            Somma B all'accumulatore
05                     │   +3211                  │            Dividi 2 all'accumulatore
06                     │   +2112                  │            Memorizza il valore dell'accumulatore in C
07                     │   +1112                  │            Stampa C
08                     │   +4300                  │            Halt
09                     │   +0000                  │            Variabile A
10                     │   +0000                  │            Variabile B
11                     │   +0000                  │             2
12                     │   +0000                  │             Risultato C

**Comment by FabioZTessitore** [comment]
ma che barra verticale hai usato per fare la tabella??? mah

**Comment by luca998** [comment]
quella dei caratteri speciali

**Comment by FabioZTessitore** [comment]
eh. E non lo fare più

**Comment by luca998** [comment]
Va bene

**Comment by FabioZTessitore** [comment]
qui non hai postato ancora la versione buona del programma della media

**Comment by luca998** [comment]
| Locazione | Numero | Istruzione |
| --- | --- | --- |
| 00 | +1009 | Leggi A |
| 01 | +1010 | Leggi B |
| 02 | +2011 | Carica 2 |
| 03 | +2009 | Carica A nell'accumulatore |
| 04 | +3010 | Somma B all'accumulatore |
| 05 | +3211 | Dividi 2 all'accumulatore |
| 06 | +2112 | Memorizza il valore dell'accumulatore in C |
| 07 | +1112 | Stampa C |
| 08 | +4300 | Halt |
| 09 | +0000 | Variabile A |
| 10 | +0000 | Variabile B |
| 11 | +0000 | 2 |
| 12 | +0000 | Risultato C |

**Comment by FabioZTessitore** [comment]
La riga 02 carica nell'accumulatore il contenuto della cella 11 (che è zero!). Devi correggere queste due cose

**Comment by luca998** [comment]
| Locazione | Numero | Istruzione |
| --- | --- | --- |
| 00 | +1009 | Leggi A |
| 01 | +1010 | Leggi B |
| 02 | +1111 | Carica 2 |
| 03 | +2009 | Carica A nell'accumulatore |
| 04 | +3010 | Somma B all'accumulatore |
| 05 | +3211 | Dividi 2 all'accumulatore |
| 06 | +2112 | Memorizza il valore dell'accumulatore in C |
| 07 | +1112 | Stampa C |
| 08 | +4300 | Halt |
| 09 | +0000 | Variabile A |
| 10 | +0000 | Variabile B |
| 11 | +0000 | 2 |
| 12 | +0000 | Risultato C |

**Comment by FabioZTessitore** [comment]
Alla posizione 11 continua a non esserci il valore 2.
Inoltre l'istruzione alla locazione 02 (giusta o sbagliata che sia) è inutile. Cosa carichi a fare il 2 nell'accumulatore?

**Comment by luca998** [comment]
Come faccio a dividere per 2 dopo?
Il 07/Feb/2016 19:22 "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Se metti il 2 in una locazione di memoria, non esiste forse una istruzione per fare la divisione?

**Comment by luca998** [comment]
Si 32
Il 07/Feb/2016 19:25 "Fabio Z Tessitore" notifications@github.com ha
scritto:
