### ISSUE TITLE
creazione branch

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/simpletron#2]
In questo progetto lavoreremo con varie branch. In ognuna svilupperai una parte del progetto e poi mettiamo tutto insieme
### visualizzare branch

Per prima cosa devi imparare a vedere quali sono le branch che hai nella tua repo (il seguente comando mostra sia quelle locali che quelle remote)

``` bash
$ git branch -a
```
### creare e cambiare branch

Per creare una nuova branch (non eseguire)

``` bash
$ git branch nome_branch
```

Per passare alla branch appena creata

``` bash
$ git checkout nome_branch
```
#### creare e cambiare branch contemporaneamente

Le due operazioni di creazione e cambio branch possono essere unificate

``` bash
$ git checkout -b nome_branch
```
## Da fare

Per cominciare crea le seguenti branch
- [x] welcome
- [x] memory
- [x] execute
- [x] cpu

**Comment by FabioZTessitore** [comment]
Le branch dove stanno?

**Comment by luca998** [comment]
le ho create
 git branch -a
  cpu_branch
  execute_branch
 master
  memory_branch
  welcome_branch
  remotes/origin/HEAD -> origin/master
  remotes/origin/master

**Comment by FabioZTessitore** [comment]
prima di tutto perché nei nomi compare _branch?

Poi dovresti fare il push

**Comment by luca998** [comment]
va bene?

**Comment by FabioZTessitore** [comment]
perfetto
