### ISSUE TITLE
welcome

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/simpletron#3]
Assicurati di essere nella branch welcome

``` bash
$ git checkout welcome
```

Scrivi un piccolo file main.c e crea una funzione welcome() che restituisce un messaggio di saluto. Nel main stampa il messaggio restituito dalla funzione welcome().

**Comment by luca998** [comment]
quando vado a fare il push lo devo fare nella welcome?

**Comment by FabioZTessitore** [comment]
Avresti dovuto lavorarci nella welcome e poi fare il push. Se sei in
difficoltà cancella la tua cartella e rifai il clone

Per passare alla welcome
git checkout welcome

Il mercoledì 3 febbraio 2016, luca998 notifications@github.com ha scritto:

**Comment by luca998** [comment]
ho aggiunto in ritardo il gitignore e mi ha caricato anche il main.c~

**Comment by FabioZTessitore** [comment]
cerca di scrivere il codice in maniera un po' più decente. Così com'è è impossibile da leggere nonostante siano poche righe.

Questo è il messaggio di benvenuto definitivo

![welcome](https://cloud.githubusercontent.com/assets/3002194/11936845/d3ee3810-a810-11e5-9856-6d7b7c049663.png)

**Comment by FabioZTessitore** [comment]
ho fatto qualche piccolo aggiustamento, soprattutto spazi. Welcome va bene così
