### ISSUE TITLE
merge welcome

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/simpletron#4]
quando avremo terminato di scrivere la funzione welcome() dobbiamo fare il merge con il master.

Per ora aspetta. finiamo prima welcome

**Comment by FabioZTessitore** [comment]
E' arrivato il momento di fare il merge di welcome in master. Sai già come fare?

**Comment by luca998** [comment]
No
Il 07/Feb/2016 19:17 "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Prima di tutto devi fare un pull per scaricare le mie modifiche

``` bash
$ git pull origin
```

Poi assicurati di essere sul ramo master

``` bash
$ git checkout master
```

Infine fai il merge di welcome

``` bash
$ git merge welcome
```

**Comment by luca998** [comment]
Ok fatto

**Comment by FabioZTessitore** [comment]
mi sa che hai fatto il contrario. Hai fatto il merge di master in welcome

fai uno screenshot del comando:

``` bash
$ git log --graph --decorate --all --oneline
```

**Comment by luca998** [comment]
![schermata del 2016-02-12 16 10 14](https://cloud.githubusercontent.com/assets/16340042/13010676/4892ddf4-d1a3-11e5-925a-91b5b922f6bd.png)

**Comment by FabioZTessitore** [comment]
ok, allora forse non hai fatto il push

**Comment by luca998** [comment]
forse si,lo faccio ora

**Comment by FabioZTessitore** [comment]
ok, ora però nel ramo welcome c'è un commit successivo a quando hai fatto il merge, quindi lo devi rifare

**Comment by luca998** [comment]
okok

**Comment by FabioZTessitore** [comment]
lo facciamo questo merge così attacchiamo con la memoria?

**Comment by luca998** [comment]
L'ho fatto

**Comment by FabioZTessitore** [comment]
non del tutto. Ti avevo avvisato che sul ramo welcome avevo fatto delle modifiche.
Prova a fare un

``` bash
$ git pull
```

e poi

``` bash
$ git log --graph --decorate --all --oneline
```

per vedere com'è la situazione

**Comment by luca998** [comment]
La situazione è come quella dello screenshot

**Comment by FabioZTessitore** [comment]
lo vedi origin/welcome che sta sopra a master e a welcome?
significa che il branch welcome che sta sul sito sta un commit avanti

devi fare così:

``` bash
$ git pull
$ git checkout welcome
$ git checkout master
$ git merge welcome
```

**Comment by luca998** [comment]
![schermata del 2016-02-17 15 22 36](https://cloud.githubusercontent.com/assets/16340042/13112307/788594f8-d58a-11e5-8c60-c906bd0a4958.png)

**Comment by FabioZTessitore** [comment]
tu sei certo di aver fatto tutti i passaggi?

**Comment by FabioZTessitore** [comment]
prova a fare così

``` bash
$ git checkout welcome
$ git pull
```

e poi

``` bash
$ git checkout master
$ git merge welcome
```

**Comment by luca998** [comment]
Sicurissimo
Il 17/Feb/2016 16:17 "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
hai provato le ultime cose che ti ho mandato?

**Comment by luca998** [comment]
Ok ho provato a rifarli e mi è uscito questo

![2](https://cloud.githubusercontent.com/assets/16340042/13115680/092e95a0-d599-11e5-9ffb-e9497b469af7.png)

**Comment by FabioZTessitore** [comment]
adesso ci siamo.

fai un push su master

``` bash
$ git push origin master
```
