### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/simpletron#5]
Per iniziare il lavoro con la memoria dobbiamo prima di tutto spostare la branch memory. Infatti l'abbiamo creata all'inizio e come puoi vedere dal log si trova ferma al primo commit.
L'operazione è un rebase (_non_ interattivo stavolta).

I passaggi sono due:
1. passare su memory
2. fare il rebase su master

``` bash
$ git checkout memory
$ git rebase master
```

quando si aprirà l'editor di testi segui le istruzioni

**Comment by luca998** [comment]
Ok ho fatto il rebase

**Comment by FabioZTessitore** [comment]
quando fai le modifiche non dimenticare il push sennò non posso seguirti

**Comment by luca998** [comment]
Ok scusate

**Comment by FabioZTessitore** [comment]
crea un file `memory.h` contenente una struttura dati `Memory`.
Una `Memory` sarà composta da un vettore di 100 interi

**Comment by FabioZTessitore** [comment]
crea una funzione memory_init che azzera gli elementi della memoria e poi una funzione memory_dump che stampa come mostrato di seguito

![memory](https://cloud.githubusercontent.com/assets/3002194/11936925/54344c76-a811-11e5-94af-9b6783ceda59.png)
